version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=django_celery_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery-worker:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=django_celery_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped
    command: celery -A django_celery_project worker --loglevel=info

  celery-beat:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=django_celery_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped
    command: celery -A django_celery_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=django_celery_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped
    command: celery -A django_celery_project flower

volumes:
  redis_data:
  static_volume: