apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  DB_NAME: "django_db"
  DB_USER: "django_user"
  DB_PASS: "Harsh@1234"
  DB_HOST: "127.0.0.1"
  GS_BUCKET_NAME: "django-bucket2025"