# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP

# Django Web Service (NodePort - No extra cost)
apiVersion: v1
kind: Service
metadata:
  name: django-web-service
  labels:
    app: django-web
spec:
  selector:
    app: django-web
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer

